.PHONY: all

all:
	valac \
		-g \
		--pkg gee-0.8 \
		--pkg gio-unix-2.0 \
		--pkg gtk+-3.0 \
		--pkg posix \
		-o ucgraph \
		main.vala \
		Application.vala \
		Deserialization.vala \
		Device.vala \
		Pin.vala \
		Port.vala \
		Protocol.vala \
		Serial.vala \
		UI/AboutDialog.vala \
		UI/Commands.vala \
		UI/PortsStore.vala \
		UI/PortsView.vala
